# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 18:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionality', models.CharField(choices=[('PA', 'Panamá'), ('CR', 'Costa Rica'), ('NI', 'Nicaragua'), ('HON', 'Honduras'), ('SAL', 'Salvador'), ('BEL', 'Belice'), ('GUA', 'Guatemala'), ('otro', 'Other nacionalities')], max_length=5, verbose_name='Nacionality')),
                ('identification', models.CharField(max_length=20, verbose_name='Identification')),
                ('born_date', models.DateField(verbose_name='Born date')),
                ('gender', models.SmallIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], verbose_name='Gender')),
                ('institution', models.CharField(blank=True, max_length=250, null=True, verbose_name='Institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
