# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preregistered', models.BooleanField(default=False, verbose_name='Pre-registered')),
                ('registered', models.BooleanField(default=False, verbose_name='Registered')),
                ('mozilla_subvention', models.BooleanField(default=False, verbose_name='Mozilla Subvention')),
                ('mozilla_subvention_description', models.TextField(blank=True, null=True, verbose_name='Why should we give you the mozilla subvention')),
                ('subvention_request', models.BooleanField(default=False, verbose_name='Subvention request')),
                ('subvention_description', models.TextField(blank=True, null=True, verbose_name='Why should we give you the subvention')),
                ('payed', models.BooleanField(default=False, verbose_name='Payed')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='alimentary_restriction',
            field=models.TextField(blank=True, null=True, verbose_name='Alimentary restriction'),
        ),
        migrations.AddField(
            model_name='profile',
            name='snore',
            field=models.BooleanField(default=False, verbose_name='Snore during sleep'),
        ),
    ]
