# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20161028_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='health_considerations',
            field=models.TextField(blank=True, null=True, verbose_name='Health considerations'),
        ),
    ]
