# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 18:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('XM', 'XM'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3, verbose_name='Size')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Amount')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
            ],
        ),
        migrations.CreateModel(
            name='TShirtStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('gender', models.CharField(choices=[('M', 'Women'), ('H', 'Man')], max_length=1, verbose_name='Gender')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='tshirt/%Y/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='tshirt/%Y/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='tshirt/%Y/')),
            ],
        ),
        migrations.AddField(
            model_name='tshirt',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tshirt.TShirtStyle', verbose_name='Style'),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
