# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 18:47
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.URLField(verbose_name='Url')),
                ('contact_email', models.EmailField(default='changeme@example.com', max_length=254, verbose_name='Contact email')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.SmallIntegerField(choices=[(1, 'First floor'), (2, 'Second floor'), (3, 'Third floor'), (4, 'Fourth floor'), (5, 'Fifth floor')], default=1, verbose_name='Floor')),
                ('number', models.CharField(max_length=15, verbose_name='Number')),
                ('total_beds', models.SmallIntegerField(default=1, verbose_name='Total beds')),
                ('matrimonial', models.BooleanField(default=False, verbose_name='Matrimonial')),
                ('available_beds', models.SmallIntegerField(default=0, verbose_name='Available beds')),
                ('price_per_bed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Price per bed')),
                ('coin', models.CharField(default='$', max_length=10, verbose_name='Pay in ')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel', verbose_name='Hotel')),
            ],
        ),
    ]
